#update_fastlane

fastlane_version "1.53.0"

default_platform :ios

platform :ios do

  desc "Check setup"
  lane :check_setup do
    Helper.log.info "Checking setup"
    sh '(cd .. && ruby scripts/test_setup.rb)'
  end

  desc "Prepares the fixtures"
  lane :fixtures_init do
    Helper.log.info "Generating metadata"
    # sh 'ruby ../bin/genimages_itc.rb ../fixtures/ios'
    # sh 'ruby ../bin/genimages_play.rb ../fixtures/android'
    puts `(cd .. ; unzip -u FastlaneIT_fixtures.zip )`
    sh 'ruby ../bin/genmetadata_itc.rb ../fixtures/ios'
  end

  desc "initialize"
  lane :meta_upload do
    fixtures_init
    deliver(metadata_path: "fixtures/ios/metadata_4",
            screenshots_path: "fixtures/ios/screenshots_4_6_5",
            skip_screenshots: true, skip_metadata: false, force: true)
  end

  lane :test_all do
    meta_upload
    sh '(cd .. && ruby scripts/run_all.rb)'
  end

end